### ISSUE TITLE
Shell doesn't terminate on Ctrl-D or EOF

### ISSUE THREAD

**Issue by trusch** [adam-mcdaniel/dune#1]
I tried exiting the shell after testing it using Ctrl-D and this didn't work. When I do something like `echo "1 + 1" | dune` I would expect to see "2" but I see the welcome screen of dune and it just hangs even without a prompt. Ctrl-C also doesnt work as expected then

**Comment by trusch** [comment]
I just skimmed the source code (ok, the bin.rs) and found that there is not much signal handling except restarting the repl on ctrl-c and there is also no check if stdin is a tty and if not skip the welcome banner etc. I guess I would even know how to add this.

If I find time in the end of the week I'll work on this if you didn't in the meantime :)

**Comment by adam-mcdaniel** [comment]
Hmm, I'm not exactly sure how to handle EOF using rustyline (or how to check for TTY in general, either); I'll have to check and see how it's supposed to be done. The reason it hangs when you pass code through STDIN, though, is that it might just continuously be reading the empty string from `readline`? I'm not exactly sure. I'll try this myself when I get back to my machine!

**Comment by trusch** [comment]
Yeah, it's the empty string from readline. In it the rustyline::EOF is swallowed and converted to a empty line. If we would have readline return an Result we should be able to handle that error one level above and break the repl loop and exit with 0 in the end.

For the tty checking part I would suggest using the atty crate. It exposes simple predicates to check stdin/out if they are a tty or not. The result of that check could be stored in the default env that is setup in application startup and then be used in the prelude to hide the welcome message.

**Comment by adam-mcdaniel** [comment]
I just added an `std::process::exit` call to the match branch for `EOF`. Running `echo "2 + 2" | dune` now prints the expected output (given you've written a `.dune-prelude` to get rid of the introduction that takes user input).

I'll look into the `atty` crate now!

**Comment by trusch** [comment]
You're a real code hero! Thanks a lot for your efforts!
