### ISSUE TITLE
Proper parsing/syntax highlighting

### ISSUE THREAD

**Issue by Aloso** [adam-mcdaniel/dune#14]
Currently syntax highlighting is pretty rudimentary: It searches for tokens without context, so strings/comments can't get highlighted properly, and tokens are erroneously highlighted within strings and comments.

While investigating, I also noticed that the parser sometimes parses keywords within identifiers:

```js
(dune) /home/ludwig$ let TrueStory = "The following is parsed as two tokens!"
(dune) /home/ludwig$ TrueStory
cannot apply `True` to the arguments [Story]
```

This shouldn't be too difficult to fix.

I'm not sure how to best implement syntax highlighting. I think the best solution is to use a tokenizer, i.e. a function that splits the input into individual tokens. This could also be used by the parser if desired.

**Comment by adam-mcdaniel** [comment]
I very much agree with the tokenization. I think we should add something like this to the `parse.rs` file:

```rs
pub enum Token {
    Operator(String),
    Keyword(String),
    StringLiteral(String),
    IntegerLiteral(String),
    FloatLiteral(String),
    BooleanLiteral(String),
    Symbol(String),
    Whitespace(String),
    Other(String),
}

fn parse_token(input: &str) -> IResult<&str, Token, SyntaxError>;
fn parse_tokens(input: &str) -> IResult<&str, Vec<Token>, SyntaxError>;
```

Then, in the `syntax_highlight` function, we call `parse_tokens` on the input string, and then just do the appropriate syntax highlighting for each token and join the results.

As for the malparsing, that shouldn't be difficult to fix: the parser is really simple. I think the problem might be that `parse_symbol` has lower priority than `parse_boolean` and `parse_none` in the `parse_expression_prec_one` function.

**Comment by Aloso** [comment]
Thanks for the feedback. I'd like to implement this. Assign me if that's ok with you.
