### ISSUE TITLE
Why is `//` used for division?

### ISSUE THREAD

**Issue by Aloso** [adam-mcdaniel/dune#20]
There doesn't seem to be a compelling reason not to use `/`.

**Comment by adam-mcdaniel** [comment]
The reason has to do with the following ambiguous expression:

```bash
echo 1 / 3
```

Do you interpret this as `echo (1 / 3)`? or `echo (1) (/) (3)` where `/` is interpreted as the folder `/`?

**Comment by Aloso** [comment]
I didn't realize that `/` is also a file path. Thanks for explaining!

**Comment by adam-mcdaniel** [comment]
No problem! :)
