### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by xyproto** [adam-mcdaniel/dune#29]
Hello,

Thanks for creating dune, I just tried it, and it's pretty fun.

If this package hypothetically were to be packaged for a Linux distro, what should the package name be?

`dune` is already taken by the build system for OCaml.

Would you prefer `adam-mcdaniel-dune` or something like `dune-shell`? Have you considered renaming the project to avoid name collisions?

Best regards,
Alexander F. Rødseth

**Comment by adam-mcdaniel** [comment]
Thanks a lot! I'm glad you enjoy it :)

I would probably prefer `dunesh` or `dune-shell` if it were added to a package manager. Of those two I'm not sure which I'd pick though. I'll definitely have to change the name of the binary in the future, I just haven't gotten around to it yet. The binary would probably be called `dunesh`

**Comment by adam-mcdaniel** [comment]
The executable name is changed to `dunesh` in the `main` branch now; the package has yet to be updated on https://crates.io with the new executable name, though.

**Comment by adam-mcdaniel** [comment]
The new executable name is reflected in [the updated package](https://crates.io/crates/dune)!

**Comment by xyproto** [comment]
Great! Could you please also create a git tag, like for instance `1.0.0`? This makes it easier to package for Linux distros.

**Comment by xyproto** [comment]
@adam-mcdaniel `dunesh` is in Arch Linux now, a release tag would be helpful. 🙂

**Comment by adam-mcdaniel** [comment]
Wow that's absolutely wonderful! I've tagged this newest release with `v0.1.7`, and all following releases will be tagged as well :)
