### ISSUE TITLE
History file location

### ISSUE THREAD

**Issue by xyproto** [adam-mcdaniel/dune#62]
The history file is created as `~/history.txt` by default. It would be better, and more conventional, if it was stored as ie. `~/.dunesh_history`, `~/.cache/dune/history.txt` or `$XDG_CACHE_DIR/dune/history.txt`.

**Comment by adam-mcdaniel** [comment]
Its stored as ~/.dune-history in the dev build now.

**Comment by xyproto** [comment]
Cool, thanks.
