### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by xyproto** [adam-mcdaniel/dune#69]
When starting Dune for the first time and typing `ls`, it works fine. However, after `cd /` I get this output when running `ls`:

```
(dune) /$ ls
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/bin.rs:440:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

There are no permission issues when running this under `zsh`, it calls `ls` and lists the files normally.

**Comment by adam-mcdaniel** [comment]
Are you sure youre running the newest version of dune? Line 440 shouldn't panic at all; it's just this parameter to `repl`:
```rs
    atomic_env: Arc<Mutex<Environment>>,
```

**Comment by xyproto** [comment]
No. I should have included the version number. I will test again with the latest release. 👍

**Comment by xyproto** [comment]
It works in 0.1.7.
