### ISSUE TITLE
touch doesn't work as expected

### ISSUE THREAD

**Issue by scaevola** [adam-mcdaniel/dune#7]
```sh
(dune) /Users/scaevola$ touch ~/.dune-prelude
touch: ~/.dune-prelude: No such file or directory
```

I want to create a file which shouldn't exist

**Comment by markpbaggett** [comment]
I don't think the issue is touch. touch works fine for me at least.  

The issue is that `~` isn't aliased / doesn't equate to your home directory.  You'll need to specify path to your home directory differently.

**Comment by Aloso** [comment]
Dune doesn't expand `~`. See issue #4.

**Comment by scaevola** [comment]
`~` is universally means `HOME` in every shell out there. If you want to build a user base, you should definitely consider to adhere to what your users automatically do in other shells.
