### ISSUE TITLE
builtin@exec seems to clash with exec subcommand

### ISSUE THREAD

**Issue by sphinxc0re** [adam-mcdaniel/dune#73]
When using docker compose, every time I use the exec command e.g.
```
docker compose exec container_name
```

I get the following error:

```
unknown docker command: "compose builtin@exec"
```

It seems to me like the `exec` subcommand clashes with the `builtin@exec` 🤔

**Comment by adam-mcdaniel** [comment]
Yes, the symbol `exec` evaluates to the builtin function by default. To circumvent this, you can either use a quoted expression like so:

```bash
$ # quote exec
$ docker compose 'exec container_name
```

Or, you can unbind exec entirely (and optionally save it in another symbol)

```bash
$ let old-exec = exec # save it
$ unbind exec # unbind symbol
```

**Comment by sphinxc0re** [comment]
Okay, I can do that but it feels more like a workaround than a fix. Shouldn't this work out-of-the-box?

EDIT: I don't know about the inner workings of the shell but would it be possible to detect when a command is a subcommand of another?

**Comment by adam-mcdaniel** [comment]
It's not a workaround if this is how you want your shell to behave; I would much rather not have symbols evaluate differently based on the structure of an expression.

Add `unbind exec` to your prelude and you won't have to run it again. Every dune shell you open from that point won't have this problem.

Also, it does work out of box in that you can explicitly circumvent the evaluation of `exec` out of the box. Think about it this way: in bash, you use the `$` symbol to denote variable usage. In dune you do the opposite: you use `'` to specify no evaluation.

**Comment by sphinxc0re** [comment]
Ah! That makes sense. It just feels a bit non-intuitive at first that some commands just work and some have to be quoted.

This might not be the ideal place to ask, but: Does this project have a chatroom somewhere (IRC, Matrix, Gitter, Discord, ...) where one can just ask questions and discuss?

**Comment by adam-mcdaniel** [comment]
Yes, it should only be the builtin functions (and whatever variables you define at the main scope) that should have this problem, and there are very few builtin functions at the main scope (most are just stored in libraries).

Also, no, there's no community at the moment. I haven't created a Discord for the shell yet, but I think that would definitely be a good idea.
