### ISSUE TITLE
`fn@filter` doesn't work

### ISSUE THREAD

**Issue by nivpgir** [adam-mcdaniel/dune#78]
this looks like a very cool project! I tried out some stuff and found that:
```
 [1, 2, 3, 4, 5] | fn@filter ( x -> x == 1 )
```
prints: `cannot add [] and item`

while:
```
fn@filter ( x -> x == 1 ) [1, 2, 3, 4, 5] 
```
works as expected and returns [1]

not sure whats the cause of the difference but I managed to fix it by changing [`fn@filters` implementation](https://github.com/adam-mcdaniel/dune/blob/c6706a73018c9526ab0c686b0044a4e50708aee5/src/binary/init/fn_module.rs#L65)

to:
```
f -> list -> { let result = [];
  for item in list { if (f item) { let result = (+ result [item]) } else (None) }; result
}
```

I've been wanting a more functional shell for a long time and I hope dunesh could turn into this for me, so I'd love to see this fixed, let me know if you need any help 😄.

**Comment by adam-mcdaniel** [comment]
Addressed by [this commit](https://github.com/adam-mcdaniel/dune/commit/612aa9a0a0a36cb73e3a1c36465768f9f2040eb5)!
