### ISSUE TITLE
Stuck at piping with pv

### ISSUE THREAD

**Issue by kenorb** [adam-mcdaniel/dune#84]
I've installed `pv` to check the speed while pipe'ing, but it doesn't work.

```
$ seq 1 1000000 | pv -l | wc -l
12.8k 0:00:33 [0.00 /s] [ <=>                                     
```

and it's stuck.

This is Bash:

```
$ seq 1 10000000 | pv -l | wc -l
10.0M 0:00:00 [69.1M/s] [ <=>                                                                           ]
10000000
```

**Comment by adam-mcdaniel** [comment]
This is because this shell doesn't actually pipe, it takes the output of a program *in full*, and then passes it as a string to the next. Not ideal, I know, but its portable and fits my needs.
